### PR TITLE
XCConfig files

### LINKED ISSUE #59: Support xcconfig
# Motivation
Auto apply xcconfig configurations like this.
xcode-configuration

# Current Problems
I notice documentations do mention about xcconfig but looks like it's not working as expected.

- Setting `configFiles` does not affect anything. (Bug? or maybe my spec is wrong)
- There is no way to set base xcconfigs for PBXProject.
- xcconfigs not being added to project

# Proposal
So this is my proposal.
- Support `baseConfiguration` for PBXProj
- Rename target's `configFiles` with `baseConfigurations` for consistency.
- (Optional) Rename `configs` to `configurations` since it looks like `xcconfig` and is misleading.

```project.yml
name: MyProject
configurations:
  Debug:
    baseConfiguration: configs/Debug.xcconfig
  OTA:
    baseConfiguration: configs/OTA.xcconfig
  Release:
    baseConfiguration: configs/Release.xcconfig
targets:
  MyApp:
    type: application
    platform: iOS
    sources: Sources/MyApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.hello
    baseConfigurations:
      Debug: configs/MyApp-Debug.xcconfig
      OTA: configs/MyApp-OTA.xcconfig
      Release: configs/MyApp-Release.xcconfig
```

If you guys feel happy with this outline, I can start working on a PR. 💪

### PR DESCRIPTION
**Pull request by yonaskolb**
Fixes #59 

- [x] fix target `configFiles`
- [x] add project `configFiles`
- [x] read xcconfig files while doing build setting lookups
- [x] add `fileGroups` to project for including non build files (like configs that don't exist in any target sources)
- [x] documentation

### CODE REVIEW

**Comment by yonaskolb** [comment]
@toshi0383 this should fix your xcconfig issues. Note that this is still using the old names

**Comment by yonaskolb** [comment]
`project.groups` and `project.settingGroups` might clash. They might be renamed as well as configs. Any suggestions? `settingGroups` used to be called `settingPresets` actually

File: Sources/XcodeGenKit/SettingsBuilder.swift [hunk 1]
```diff
@@ -57,15 +57,19 @@ extension ProjectSpec {
...
     }
 
-    // combines all levels of a target's settings
+    // combines all levels of a target's settings: target, target config, project, project config
     public func getCombinedBuildSettings(basePath: Path, target: Target, config: Config, includeProject: Bool) -> BuildSettings {
         var buildSettings: BuildSettings = [:]
         if includeProject {
+            if let configFilePath = configFiles[config.name] {
+                if let configFile = try? XCConfig(path: basePath + configFilePath) {
+                    buildSettings += configFile.flattenedBuildSettings()
```
Comment (toshi0383) [inline Sources/XcodeGenKit/SettingsBuilder.swift]: Maybe including xcconfig should just `#include` the included xcconfig, not adding to buildSettings section.🤔
What do you think?

Comment (toshi0383) [reply Sources/XcodeGenKit/SettingsBuilder.swift]: Oh and what if included xcconfig `#include` other xcconfigs?

Comment (yonaskolb) [reply Sources/XcodeGenKit/SettingsBuilder.swift]: Not sure what you mean by the first point? Maybe these will answer your question.
- this function is just use for getting all the combined settings for the purposes of checking what build settings will be applied - similar to Xcode's `combined` settings view
- xcconfigs aren't added using #include they are just set as a baseconfiguration for the target or project. The rest of the build settings are applied directly on the build setting or project and don't use an xcconfig

For the second point `configFile. flattenedBuildSettings()` goes through all #include files and merges them 👍

Comment (toshi0383) [reply Sources/XcodeGenKit/SettingsBuilder.swift]: Understood. I'm going to take a look at the details.👌

File: Fixtures/TestProject/TestProject.xcodeproj/project.pbxproj [hunk 2]
```diff
@@ -102,9 +104,20 @@
 			path = TestProjectTests;
 			sourceTree = "<group>";
 		};
+		CC9392641F76EDE600C1934A /* Configs */ = {
```
Comment (toshi0383) [inline Fixtures/TestProject/TestProject.xcodeproj/project.pbxproj]: How did you create this `TestProject.xcodeproj/project.pbxproj` ?
On Xcode, `Configs` group is missing reference (appears red).

File: Sources/XcodeGenKit/SettingsBuilder.swift (hunk 1 above)
Comment (toshi0383) [reply Sources/XcodeGenKit/SettingsBuilder.swift]: > For the second point configFile. flattenedBuildSettings() goes through all #include files and merges them 👍

What I meant was `XcodeGen:Include`, I but I see `XcodeGen:Include` just ignores `XcodeGen:Include`ed spec's `configFile`, so it's no problem.

```
TestProject $ head spec.yml
include: included.yml
name: GeneratedProject
groups:
  - Configs
targets:
  TestProject:
    type: application
    platform: iOS
    sources: TestProject
    settings:
TestProject $ head included.yml
configFiles:
  Debug: Included/Configs/included.xcconfig  # This is completely ignored when `XcodeGen:included`.
```
This behavior is perfectly 🙆‍♂️ to me. Maybe it worth it to warn user when `XcodeGen:included` spec has configFile attribute, because it's ignored.

Maybe we should really rename `XcodeGen:include` to something else to avoid confusion. 🙄

**Comment by toshi0383** [comment]
> project.groups and project.settingGroups might clash. They might be renamed as well as configs. Any suggestions? settingGroups used to be called settingPresets actually

I've read the documentation.
Looks like it's useful feature, too. I think it should be `buildSettings` and `buildSettingsGroup` to be explicit.

File: Sources/XcodeGenKit/SettingsBuilder.swift (hunk 1 above)
Comment (yonaskolb) [reply Sources/XcodeGenKit/SettingsBuilder.swift]: That's because include is a list not just a string. I should change this though to allow a simple string for a single value, just like a target's sources:
```
include: [included.yml] #works, using json style
include:
  - included.yml #works, using yaml style
include: included.yml #does work (yet, will change)
```

File: Fixtures/TestProject/TestProject.xcodeproj/project.pbxproj (hunk 2 above)
Comment (yonaskolb) [reply Fixtures/TestProject/TestProject.xcodeproj/project.pbxproj]: The `TestProject.xcodeproj` was created and edited in Xcode. `GeneratedProject.xcodeproj` is the one generated by XcodeGen.

I'm not sure what you mean by missing configs group. Both projects appear fine for me

File: docs/ProjectSpec.md [hunk 3]
```diff
@@ -29,9 +29,11 @@ Required properties are marked 🔵 and optional properties with ⚪️.
 - ⚪️ **options**: [Options](#options) - Various options to override default behaviour
 - ⚪️ **attributes**: `map` - The PBXProject attributes. This is for advanced use. Defaults to ``{"LastUpgradeCheck": "0900"}``
 - ⚪️ **configs**: [Configs](#configs) - Project build configurations. Defaults to `Debug` and `Release` configs
+- ⚪️ **configFiles**: [Config Files](#config-files) - `.xcconfig` files per config
 - ⚪️ **settings**: [Settings](#settings) - Project specific settings. Default base and config type settings will be applied first before any settings defined here
 - ⚪️ **settingGroups**: [Setting Groups](#setting-groups) - Setting groups mapped by name
 - ⚪️ **targets**: [Target](#target) - The list of targets in the project mapped by name
+- ⚪️ **fileGroups**: `[String]` - A list of paths to add to the top level groups. These are files that aren't build files but that you'd like in the project heirachy. For example a folder xcconfig files that aren't already added by any target sources.
```
Comment (pepibumur) [inline docs/ProjectSpec.md]: there's a typo `heirachy` ~> `hierarchy`

File: Sources/XcodeGenKit/SettingsBuilder.swift (hunk 1 above)
Comment (yonaskolb) [reply Sources/XcodeGenKit/SettingsBuilder.swift]: `include` can now be a single string https://github.com/yonaskolb/XcodeGen/commit/39c8af324c88f0e43f7131c5791f718a1eb29de6

File: Fixtures/TestProject/TestProject.xcodeproj/project.pbxproj (hunk 2 above)
Comment (yonaskolb) [reply Fixtures/TestProject/TestProject.xcodeproj/project.pbxproj]: I just saw what you mean by the red group, I've fixed this in master. This project isn't really used in any tests and is more just for a comparison between a project created in xcode versus created in XcodeGen
