### PR TITLE
Transform input spec path to absolute path

### LINKED ISSUE #183: createIntermediateGroups ends up with broken file refs
With this project configuration:

```yaml
name: Project
options:
  createIntermediateGroups: True
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Modules/Sources
      - Foo/Sources
```

And this folder structure:

```
.
├── Foo
│   └── Sources
│       └── baz.swift
├── Modules
│   └── Sources
│       └── bar.swift
└── project.yml
```

Running XcodeGen results in a broken project file:

screen shot 2017-12-05 at 16 32 41

Example setup: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1533449/XcodeGenTest.zip)

### PR DESCRIPTION
**Pull request by kastiglione**
Fixes #183

As mentioned in #183, `createIntermediateGroups` fails to work as expected under certain conditions. Specifically, project generation works when the `--spec` path is absolute, but breaks when using a relative path. The solution in this change is to convert the spec path to be absolute, at the beginning of project generation.

### CODE REVIEW

File: Sources/XcodeGen/main.swift [hunk 1]
```diff
@@ -21,7 +21,7 @@ func generate(spec: String, project: String, isQuiet: Bool, justVersion: Bool) {
         exit(1)
     }
 
-    let specPath = Path(spec).normalize()
+    let specPath = Path(URL(fileURLWithPath: spec).path).normalize()
```
Comment (kastiglione) [inline Sources/XcodeGen/main.swift]: I didn't see any code in PathKit to do this.

Comment (kastiglione) [reply Sources/XcodeGen/main.swift]: I am mistaken, I can change this to `absolute()`.

Comment (yonaskolb) [reply Sources/XcodeGen/main.swift]: Yep, absolute 👍

**Comment by yonaskolb** [comment]
Thanks @kastiglione! 👏
